### ISSUE TITLE
Exception: argument --input: conflicting option string: --input

### ISSUE THREAD

**Issue by BermineCN** [sufengniu/GVIN#1]
### When I try to run the rl_nstep.py with the given data irregular100.mat, I met the following error. It seems that the 'input' argument has been defined somewhere besides the tf.flags. On the other hand, if I run this python file with the given data irregular10.mat, it is OK. I'm feeling doubtable. Could somebody tell me why? Thanks in advance. 

----------------------------------------------------------------------------------------------- 
Error
Traceback (most recent call last):
  File "C:\Program Files\Anaconda3\lib\unittest\case.py", line 58, in testPartExecutor
    yield
  File "C:\Program Files\Anaconda3\lib\unittest\case.py", line 600, in run
    testMethod()
  File "C:\Program Files\Anaconda3\lib\site-packages\nose\failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "C:\Program Files\Anaconda3\lib\site-packages\nose\loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "C:\Program Files\Anaconda3\lib\site-packages\nose\importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "C:\Program Files\Anaconda3\lib\site-packages\nose\importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "C:\Program Files\Anaconda3\lib\imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "C:\Program Files\Anaconda3\lib\imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "D:\project\GVIN_IR_Large\rl_nstep.py", line 19, in <module>
    tf.app.flags.DEFINE_string('input',           '../GVIN-master/data/irregular100.mat', 'Path to data')
  File "C:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\platform\flags.py", line 80, in DEFINE_string
    _define_helper(flag_name, default_value, docstring, str)
  File "C:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\platform\flags.py", line 65, in _define_helper
    type=flagtype)
  File "C:\Program Files\Anaconda3\lib\argparse.py", line 1344, in add_argument
    return self._add_action(action)
  File "C:\Program Files\Anaconda3\lib\argparse.py", line 1707, in _add_action
    self._optionals._add_action(action)
  File "C:\Program Files\Anaconda3\lib\argparse.py", line 1548, in _add_action
    action = super(_ArgumentGroup, self)._add_action(action)
  File "C:\Program Files\Anaconda3\lib\argparse.py", line 1358, in _add_action
    self._check_conflict(action)
  File "C:\Program Files\Anaconda3\lib\argparse.py", line 1497, in _check_conflict
    conflict_handler(action, confl_optionals)
  File "C:\Program Files\Anaconda3\lib\argparse.py", line 1506, in _handle_conflict_error
    raise ArgumentError(action, message % conflict_string)
Exception: argument --input: conflicting option string: --input
-----------------------------------------------------------------------------------------------------

**Comment by sufengniu** [comment]
We haven't tried on Windows machine yet, the error message indicates some problems with input arguments, Can you check the directory path and if file correctly located?

**Comment by BermineCN** [comment]
I have one problem when I use the trained model to make predictions according to new data. Firstly, I trained the model in the file irregular/RL with the given data, and used the tf.train.Saver to save the structure. The code to save the model is added to the rl_nstep.py as follows. I got the following 4 documents.
`saver.save(sess, './gvin')`
![default](https://user-images.githubusercontent.com/19373371/38927942-48db82c6-4342-11e8-8ad2-c93c1e5a85e0.PNG)
In another python script, I use the following code to restore the trained model.
```
with tf.Session() as sess:
  new_saver = tf.train.import_meta_graph('./gvin.meta')
  new_saver.restore(sess, tf.train.latest_checkpoint('./')
  #sess.run(tf.local_variables_initializer())
```
I got the following error message.
`FailedPreconditionError (see above for traceback): Attempting to use uninitialized value q/p_0/fc_1/weights`
If I uncomment the following code
`sess.run(tf.local_variables_initializer())`
The error message becomes to the following:
`FailedPreconditionError (see above for traceback): Attempting to use uninitialized value q/p_8/fc_2/weights`
I'm really curious about this since the saver should have saved the values of all the weights. Could you tell me why? The following is the whole error message information.

```
Traceback (most recent call last):
  File "C:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1039, in _do_call
    return fn(*args)
  File "C:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1021, in _run_fn
    status, run_metadata)
  File "C:\Program Files\Anaconda3\lib\contextlib.py", line 66, in __exit__
    next(self.gen)
  File "C:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.FailedPreconditionError: Attempting to use uninitialized value q/p_0/fc_1/weights
	 [[Node: q/p_0/fc_1/weights/read = Identity[T=DT_FLOAT, _class=["loc:@q/p_0/fc_1/weights"], _device="/job:localhost/replica:0/task:0/gpu:0"](q/p_0/fc_1/weights)]]
	 [[Node: q/Reshape_20/_737 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_439_q/Reshape_20", tensor_type=DT_INT32, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/PycharmProjects/GVIN_RL_restore/rl_nstep.py", line 137, in <module>
    next_step = sess.run(logits, fd)
  File "C:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 778, in run
    run_metadata_ptr)
  File "C:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 982, in _run
    feed_dict_string, options, run_metadata)
  File "C:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1032, in _do_run
    target_list, options, run_metadata)
  File "C:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1052, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.FailedPreconditionError: Attempting to use uninitialized value q/p_0/fc_1/weights
	 [[Node: q/p_0/fc_1/weights/read = Identity[T=DT_FLOAT, _class=["loc:@q/p_0/fc_1/weights"], _device="/job:localhost/replica:0/task:0/gpu:0"](q/p_0/fc_1/weights)]]
	 [[Node: q/Reshape_20/_737 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_439_q/Reshape_20", tensor_type=DT_INT32, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

Caused by op 'q/p_0/fc_1/weights/read', defined at:
  File "C:/Users/PycharmProjects/GVIN_RL_restore/rl_nstep.py", line 66, in <module>
    logits, nn = q_net.build_model()
  File "C:\Users\PycharmProjects\GVIN_RL_restore\model.py", line 39, in build_model
    return self.build_ir_Block_coord()
  File "C:\Users\PycharmProjects\GVIN_RL_restore\model.py", line 62, in build_ir_Block_coord
    coeff = kernel_net_coord(self.Coord, self.Dist, self.train, self.config)
  File "C:\Users\PycharmProjects\GVIN_RL_restore\model.py", line 16, in kernel_net_coord
    x = slim.fully_connected(x, 32, activation_fn=tf.nn.relu, weights_initializer=tf.truncated_normal_initializer(stddev=0.01), scope="fc_1")
  File "C:\Program Files\Anaconda3\lib\site-packages\tensorflow\contrib\framework\python\ops\arg_scope.py", line 181, in func_with_args
    return func(*args, **current_args)
  File "C:\Program Files\Anaconda3\lib\site-packages\tensorflow\contrib\layers\python\layers\layers.py", line 1433, in fully_connected
    outputs = layer.apply(inputs)
  File "C:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\layers\base.py", line 320, in apply
    return self.__call__(inputs, **kwargs)
  File "C:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\layers\base.py", line 286, in __call__
    self.build(input_shapes[0])
  File "C:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\layers\core.py", line 123, in build
    trainable=True)
  File "C:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 1049, in get_variable
    use_resource=use_resource, custom_getter=custom_getter)
  File "C:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 948, in get_variable
    use_resource=use_resource, custom_getter=custom_getter)
  File "C:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 349, in get_variable
    validate_shape=validate_shape, use_resource=use_resource)
  File "C:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 1389, in wrapped_custom_getter
    *args, **kwargs)
  File "C:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\layers\base.py", line 275, in variable_getter
    variable_getter=functools.partial(getter, **kwargs))
  File "C:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\layers\base.py", line 228, in _add_variable
    trainable=trainable and self.trainable)
  File "C:\Program Files\Anaconda3\lib\site-packages\tensorflow\contrib\layers\python\layers\layers.py", line 1334, in layer_variable_getter
    return _model_variable_getter(getter, *args, **kwargs)
  File "C:\Program Files\Anaconda3\lib\site-packages\tensorflow\contrib\layers\python\layers\layers.py", line 1326, in _model_variable_getter
    custom_getter=getter, use_resource=use_resource)
  File "C:\Program Files\Anaconda3\lib\site-packages\tensorflow\contrib\framework\python\ops\arg_scope.py", line 181, in func_with_args
    return func(*args, **current_args)
  File "C:\Program Files\Anaconda3\lib\site-packages\tensorflow\contrib\framework\python\ops\variables.py", line 262, in model_variable
    use_resource=use_resource)
  File "C:\Program Files\Anaconda3\lib\site-packages\tensorflow\contrib\framework\python\ops\arg_scope.py", line 181, in func_with_args
    return func(*args, **current_args)
  File "C:\Program Files\Anaconda3\lib\site-packages\tensorflow\contrib\framework\python\ops\variables.py", line 217, in variable
    use_resource=use_resource)
  File "C:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 341, in _true_getter
    use_resource=use_resource)
  File "C:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 714, in _get_single_variable
    validate_shape=validate_shape)
  File "C:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\ops\variables.py", line 197, in __init__
    expected_shape=expected_shape)
  File "C:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\ops\variables.py", line 316, in _init_from_args
    self._snapshot = array_ops.identity(self._variable, name="read")
  File "C:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\ops\gen_array_ops.py", line 1338, in identity
    result = _op_def_lib.apply_op("Identity", input=input, name=name)
  File "C:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 768, in apply_op
    op_def=op_def)
  File "C:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 2336, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "C:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 1228, in __init__
    self._traceback = _extract_stack()

FailedPreconditionError (see above for traceback): Attempting to use uninitialized value q/p_0/fc_1/weights
	 [[Node: q/p_0/fc_1/weights/read = Identity[T=DT_FLOAT, _class=["loc:@q/p_0/fc_1/weights"], _device="/job:localhost/replica:0/task:0/gpu:0"](q/p_0/fc_1/weights)]]
	 [[Node: q/Reshape_20/_737 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_439_q/Reshape_20", tensor_type=DT_INT32, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]
```
